'use client';

import Link from 'next/link';
import { Clock, ShieldAlert } from 'lucide-react';

export default function SignupPage() {
  return (
    <div className="flex items-center justify-center min-h-screen px-4 py-6 sm:py-10 bg-gray-50 dark:bg-gray-900">
      <div className="w-full max-w-md p-8 border rounded-xl shadow-lg bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700">
        <div className="text-center mb-6">
          <div className="flex justify-center mb-4">
            <div className="bg-blue-600 p-3 rounded-lg">
              <Clock className="h-8 w-8 text-white" />
            </div>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 dark:text-white mb-2">
            Employee Registration
          </h1>
        </div>

        <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4 mb-6">
          <div className="flex items-start gap-3">
            <ShieldAlert className="h-5 w-5 text-amber-600 dark:text-amber-400 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="font-semibold text-amber-900 dark:text-amber-200 mb-2">
                Admin/HR Only
              </h3>
              <p className="text-sm text-amber-800 dark:text-amber-300">
                Employee registration is restricted to administrators and HR officers only. 
                If you need to create an employee account, please contact your system administrator 
                or log in as an admin/HR officer.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-4 text-sm text-gray-600 dark:text-gray-400">
          <div>
            <h4 className="font-semibold text-gray-900 dark:text-white mb-2">How it works:</h4>
            <ul className="list-disc list-inside space-y-1 ml-2">
              <li>Only Admin/HR officers can create employee accounts</li>
              <li>Login ID is automatically generated by the system</li>
              <li>Password is auto-generated and can be changed after first login</li>
              <li>Employees receive their credentials from their HR department</li>
            </ul>
          </div>
        </div>

        <div className="mt-6 pt-6 border-t border-gray-200 dark:border-gray-700">
          <p className="text-sm text-center text-gray-600 dark:text-gray-400 mb-4">
            Already have an account?
          </p>
          <Link
            href="/auth/login"
            className="block w-full py-3 text-center font-semibold text-white bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600 rounded-lg transition-colors duration-200"
          >
            Sign In
          </Link>
        </div>
      </div>
    </div>
  );
}
